### PR TITLE
First pull request of code

### PR DESCRIPTION
**Pull request by kalkairis**
The queue tests are FINALLY working.
This was extremely annoying, but I am very excited about it.

Take a look and see if you have any comments - if not I will commit my changes in LabData as well.

### CODE REVIEW

**Comment by kalkairis** [comment]
Looks like you are running from your own machine.
I don't think you can run queue from your local machine at all. Only from the cluster.

**Comment by erans99** [comment]
I know but it should go to the fakeqp no?
I will check, I think the local_config should do it but it should be added to the project

**Comment by erans99** [comment]
Did fakeqp work for you?? 
Passes the unitests?
When I switch to it, I get that it does not have a terminate function (which it does not) 
You also call _qp__permanentRun which does not seem to exist anywhere

**Comment by kalkairis** [comment]
These tests were written explicitly for qp, not fakeqp.
I can change the tests to fit both, but for now they should not work for both

**Comment by erans99** [comment]
Can you make it work for fakeqp as well? this way the test will run for those also working with it locally

**Comment by kalkairis** [comment]
I fixed the issues, you are welcome to review both in fakeqp and in qp status, it worked for me.

**Pull request merged**
